
import { Room, Translations } from './types';

export const translations: Translations = {
  en: {
    // General
    login: 'Login',
    username: 'Username',
    password: 'Password',
    logout: 'Logout',
    sunriver_hotel: 'Sunriver Hotel',
    sunriver_hotel_th: 'โรงแรมซันริเวอร์',
    // Nav
    home: 'Home',
    room_status: 'Room Status',
    dashboard: 'Dashboard',
    cleaning: 'Cleaning',
    receipt: 'Receipt',
    // Home
    booking_overview: 'Booking Overview',
    add_booking: 'Add Booking',
    vacant: 'Vacant',
    booked: 'Booked',
    today_overview: "Today's Overview",
    check_in: 'Check-in',
    check_out: 'Check-out',
    in_house: 'In-House',
    no_guests_today: 'No guests for this category today.',
    // Booking Form
    booking_details: 'Booking Details',
    customer_name: 'Customer Name',
    phone: 'Phone',
    check_in_date: 'Check-in Date',
    check_out_date: 'Check-out Date',
    rooms: 'Rooms',
    booking_status: 'Booking Status',
    paid: 'Paid',
    deposit: 'Deposit',
    unpaid: 'Unpaid',
    deposit_amount: 'Deposit Amount',
    total_price: 'Total Price',
    email: 'Email',
    address: 'Address',
    tax_id: 'Tax ID',
    save_booking: 'Save Booking',
    delete_booking: 'Delete Booking',
    confirm_delete_booking_message: 'Are you sure you want to delete this booking?',
    // Room Status
    sort_by: 'Sort by:',
    room_no: 'Room No.',
    room_type: 'Room Type',
    bed_type: 'Bed Type',
    // Cleaning
    cleaning_status: 'Cleaning Status',
    clean: 'Clean',
    needs_cleaning: 'Needs Cleaning',
    confirm_cleaning_status_change: 'Confirm Status Change',
    confirm_cleaning_status_message: 'Are you sure you want to change the status for room {roomNumber} to {status}?',
    confirm: 'Confirm',
    cancel: 'Cancel',
    occupancy_status: 'Occupancy Status',
    // Receipt
    generate_receipt: 'Generate Receipt',
    search_booking: 'Search by name, phone, check-in, or booking ID...',
    recent_bookings: 'Recent Bookings',
    no_booking_selected: 'No booking selected.',
    print_receipt: 'Print Receipt',
    payment_information: "Payment Information",
    payment_method: "Payment Method",
    payment_date: "Payment Date",
    cash: "Cash",
    transfer: "Transfer",
    // more
    edit_booking: "Edit Booking",
    close: "Close",
    select_rooms: "Select Rooms",
    no_rooms_available: "No rooms available for the selected dates.",
    customer_info: "Customer Information",
    booking_id: "Booking ID",
    select_booking: "Select Booking",
    combine_bookings: "Combine Bookings",
    combined_receipt: "Combined Receipt",
    select_at_least_one_room: "Please select at least one room to save the booking.",
  },
  th: {
    // General
    login: 'เข้าสู่ระบบ',
    username: 'ชื่อผู้ใช้',
    password: 'รหัสผ่าน',
    logout: 'ออกจากระบบ',
    sunriver_hotel: 'Sunriver Hotel',
    sunriver_hotel_th: 'โรงแรมซันริเวอร์',
    // Nav
    home: 'หน้าหลัก',
    room_status: 'สถานะห้องพัก',
    dashboard: 'แดชบอร์ด',
    cleaning: 'การทำความสะอาด',
    receipt: 'ใบเสร็จ',
    // Home
    booking_overview: 'ภาพรวมการจอง',
    add_booking: 'เพิ่มการจอง',
    vacant: 'ว่าง',
    booked: 'จองแล้ว',
    today_overview: 'ภาพรวมวันนี้',
    check_in: 'เช็คอิน',
    check_out: 'เช็คเอาท์',
    in_house: 'กำลังเข้าพัก',
    no_guests_today: 'ไม่มีแขกสำหรับหมวดหมู่นี้ในวันนี้',
    // Booking Form
    booking_details: 'รายละเอียดการจอง',
    customer_name: 'ชื่อลูกค้า',
    phone: 'เบอร์โทรศัพท์',
    check_in_date: 'วันที่เช็คอิน',
    check_out_date: 'วันที่เช็คเอาท์',
    rooms: 'ห้องพัก',
    booking_status: 'สถานะการจอง',
    paid: 'ชำระแล้ว',
    deposit: 'มัดจำ',
    unpaid: 'ยังไม่ชำระ',
    deposit_amount: 'จำนวนเงินมัดจำ',
    total_price: 'ราคารวม',
    email: 'อีเมล',
    address: 'ที่อยู่',
    tax_id: 'เลขประจำตัวผู้เสียภาษี',
    save_booking: 'บันทึกการจอง',
    delete_booking: 'ลบการจอง',
    confirm_delete_booking_message: 'คุณแน่ใจหรือไม่ว่าต้องการลบการจองนี้?',
    // Room Status
    sort_by: 'เรียงตาม:',
    room_no: 'เลขห้อง',
    room_type: 'ประเภทห้อง',
    bed_type: 'ประเภทเตียง',
    // Cleaning
    cleaning_status: 'สถานะการทำความสะอาด',
    clean: 'ทำความสะอาดแล้ว',
    needs_cleaning: 'ยังไม่ทำความสะอาด',
    confirm_cleaning_status_change: 'ยืนยันการเปลี่ยนสถานะ',
    confirm_cleaning_status_message: 'คุณแน่ใจหรือไม่ว่าต้องการเปลี่ยนสถานะของห้อง {roomNumber} เป็น {status}?',
    confirm: 'ยืนยัน',
    cancel: 'ยกเลิก',
    occupancy_status: 'สถานะการเข้าพัก',
    // Receipt
    generate_receipt: 'ออกใบเสร็จ',
    search_booking: 'ค้นหาจากชื่อ, เบอร์โทร, วันเช็คอิน, หรือรหัสการจอง...',
    recent_bookings: 'การจองล่าสุด',
    no_booking_selected: 'ยังไม่ได้เลือกการจอง',
    print_receipt: 'พิมพ์ใบเสร็จ',
    payment_information: "ข้อมูลการชำระเงิน",
    payment_method: "ช่องทางการชำระเงิน",
    payment_date: "วันที่ชำระเงิน",
    cash: "เงินสด",
    transfer: "โอน",
    // more
    edit_booking: "แก้ไขการจอง",
    close: "ปิด",
    select_rooms: "เลือกห้องพัก",
    no_rooms_available: "ไม่มีห้องว่างสำหรับวันที่เลือก",
    customer_info: "ข้อมูลลูกค้า",
    booking_id: "รหัสการจอง",
    select_booking: "เลือกการจอง",
    combine_bookings: "รวมการจอง",
    combined_receipt: "ใบเสร็จรวม",
    select_at_least_one_room: "กรุณาเลือกอย่างน้อย 1 ห้องเพื่อบันทึกการจอง",
  }
};
